### ISSUE TITLE
Kurse: nach dem Erstellen wird der erstellte Kurs nicht in der Liste angezeigt

### ISSUE THREAD

**Issue by robogito** [robogito/kubus#23]
Der neue Kurs soll in der Liste erscheinen, sonst muss der Benutzer die Seite aktualisieren.
Nach dem Speichern passiert nichts und die Kursliste wird nicht mehr angezeigt.

Fehler:

app-Bm4J28Ht.js:35 Error
    at eS (index-DnbLmBsx.js:259:458)
    at index-DnbLmBsx.js:259:1105
    at index-DnbLmBsx.js:31:7832
    at async HTMLButtonElement.L (index-DnbLmBsx.js:259:9866)

**Comment by luflow** [comment]
Bekannt, schauen wir uns an.
